### ISSUE TITLE
codeserver startup options

### ISSUE THREAD

**Issue by vnijs** [dirkcgrunwald/jupyter_codeserver_proxy-#1]
Thanks for making your work available on github @dirkcgrunwald ! Much appreciated. There are a couple of customizations I'd like to add to the setup in my docker container for when code-server is started (see below). Could you tell me the best place to add these?

I tried editing _init_.py in a fork but it doesn't seem to work so far. Any suggestions perhaps? Also, connecting to a running jupyter throws and error. Have you, by chance, gotten this to work?

https://github.com/vnijs/jupyter_codeserver_proxy/blob/master/jupyter_codeserver_proxy/__init__.py

I have one more a question. When I startup code-server, with the home-directory on the host system mounted, code-server is *very* slow reading directory structures (see also issue https://github.com/codercom/code-server/issues/278). Have you come across this issue and, if so, do you have any suggestions?

**Comment by vnijs** [comment]
Made some progress on my question about slow file browsing. It should be possible to reduce fs.inotify.max_user_watches. However, even as root I get a "read.only file system" error for the below for run in a Dockerfile

```
RUN echo "fs.inotify.max_user_watches=8192" >> /etc/sysctl.conf \
  && sysctl -p
```

**Comment by dirkcgrunwald** [comment]
Sorry for delaying in responding - they way we're using this is in a Zero to JupyterHub (https://zero-to-jupyterhub.readthedocs.io/en/latest/) setup, managed with Kubernetes on GCK.

Our students have a 2GB private volume as their home directory, and that may limit the slow open behavior you've seen -- I haven't seen it in our setup, but I have seen slow scanning behavior from my Mac install of VSCode.

Let me see if I can find a way to adjust those settings.

**Comment by vnijs** [comment]
I was talking to someone today and he reminded me that since docker containers share the kernel with their host os, If you were able to change `max_user_watches` it would not only affect the container, but the host os and all other containers as well.

It would be great if there was a way to set the `max_user_watches` specifically for vscode but I'm not sure that exists. Or, alternatively, only have "tracking" on when you are in a vscode project where, presumably, you do want to track files

Question: Are you able to connect vscode to jupyter in the container? I tried (briefly) but got an error. Do you have setup information perhaps that I could take a look at?

Thanks

**Comment by vnijs** [comment]
@dirkcgrunwald FYI I forked your repo and made a few minor changes to set the working directory used when code-server starts up. That limits the slow-to-start issue. See links below for more information.

Question: I'd like to have students connect to a "Python interactive" (jupyter) session when they use the container. This works fine from vscode installed on my mac but throws an error with code-server. Have you had any success with this perhaps?

https://github.com/radiant-rstats/docker/blob/master/rsm-editors/Dockerfile
https://github.com/vnijs/jupyter_codeserver_proxy/blob/master/jupyter_codeserver_proxy/__init__.py

**Comment by vnijs** [comment]
FYI With the [development](https://pvsc.blob.core.windows.net/extension-builds/ms-python-insiders.vsix) version of the ms-python extension I am now able to connect jupyter. Very nice!
