### ISSUE TITLE
Question about SQL kernel

### ISSUE THREAD

**Issue by vnijs** [dirkcgrunwald/jupyter_codeserver_proxy-#2]
You posted the image below [here](https://github.com/jupyterhub/jupyter-server-proxy/issues/106#issuecomment-547520341) recently and I'm very interested to know more about the SQL kernel you seem to have setup. 

I looked at BeakerX but could never get that working properly. The only other one I have seen is https://teradata.github.io/jupyterextensions but that seems to be specific to vantage.

Could you provide more information? Thanks!

![image](https://user-images.githubusercontent.com/2998956/68618807-08031980-047f-11ea-98f2-4165dd30664b.png)

**Comment by dirkcgrunwald** [comment]
I uploaded the Dockerfile we use to produce the student notebook at https://gist.github.com/dirkcgrunwald/1a768256909c9f489b7ebd66005dfcfe

Our application of JupyterHub is to have an online "coding environment" for students for a range of introductory computing classes. Students use the environment for CS1 (intro prog.), CS2 (data structures) as well as computer systems, databases and now some high performance computing classes.

As part of that, we use VScode (our classes previously used cloud9 or c9.io for this).

I forgot what brings in the SQL library, but I believe it's beaker.

**Comment by vnijs** [comment]
Thanks @dirkcgrunwald! Glad to hear it is working reliably for you. Haven't had [much luck](https://github.com/twosigma/beakerx/issues/7867) getting beakerx to run reliably with Docker (using pip) but now I'll give it another try.
